# -*- coding: utf-8 -*-
"""mapper4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zrNTNVizFENkAOxuQlT0ZknktafEXdT4
"""

import sys
import re

def reducir(txt):
  print(txt)

def procesar(texto):
  txt=""
  txt1=""
  txt2=""
  txt3=""
  cont1=0
  cont2=0
  cont3=0
  for i in range(len(texto)):
    if cont2==1:
      if texto[i]=="-":
        cont3=cont3+1
      if cont3==0 and texto[i]!=",":
        txt1=txt1+texto[i]
    if texto[i]=="{":
      cont1=cont1+1
    if texto[i]==",":
      cont2=cont2+1
  cont1=0
  cont2=0
  cont3=0
  for i in range(len(texto)):
    if cont2==2:
      if texto[i]=="-":
        cont3=cont3+1
      if cont3==0 and texto[i]!=",":
        txt3=txt3+texto[i]
    if texto[i]=="{":
      cont1=cont1+1
    if texto[i]==",":
      cont2=cont2+1
  cont1=0
  cont2=0
  cont3=0
  for i in range(len(texto)):
    if cont2==8:
      if texto[i]=="-":
        cont3=cont3+1
      if cont3==0 and texto[i]!=",":
        txt2=txt2+texto[i]
    if texto[i]=="{":
      cont1=cont1+1
    if texto[i]==",":
      cont2=cont2+1
  if txt2=="STAMFORD" and txt3=="2015":
    txt=txt1+" "+txt3+" "+txt2
  if cont1>=1:
    return txt
  else:
    return ""



for line in sys.stdin:
  print("\n")
  reducir(procesar(line))

procesar("Transaction unique identifier,Price,Date of Transfer,Property Type,Old/New,Duration,Town/City,District,County,PPDCategory Type,Record Status - monthly file only")

reducir(procesar("{81B82214-7FBC-4129-9F6B-4956B4A663AD},25000,2015-08-18 00:00,T,N,F,OLDHAM,OLDHAM,STAMFORD,A,A"))