# -*- coding: utf-8 -*-
"""reducer4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aSh0J7OiSVh-PG4J7VmPYg1WWPMbEAOU
"""

import sys
import re

def procesar(texto):
  arrayText=[]
  txt=""
  
  for i in range(len(texto)):
    if texto[i]!="\n":
      txt=txt+texto[i]
    if texto[i]=="\n" or i==len(texto)-1:
      arrayText.append(txt)
      txt=""
  return arrayText
  

def reducir(arreglo):
  new_texto=[]
  value=[]
  lista=[]
  for i in range(len(arreglo)):
    aux=arreglo[i]
    contaux=0
    txt_aux=""
    val_aux=""
    for j in range(len(aux)):
      if aux[j]!="\t":
        contaux=contaux+1
      if contaux>5:
        txt_aux=txt_aux+aux[j]
      if contaux<=5:
        val_aux=val_aux+aux[j]

    new_texto.append(txt_aux)
    print(txt_aux)
    value.append(int(val_aux))

  for i in range(len(arreglo)):
    lista.append([new_texto[i],value[i]])

  new_lista=[]
  divisor=[]

  diccionario = dict()
  for p in new_texto:
    diccionario[p] = diccionario.get(p, 0)+1

  for clave in diccionario:
    divisor.append([clave,diccionario[clave]])

  for i in range(len(new_lista)):
    print(new_lista[i])



texto="25000 2015 STAMFORD\n20000 2015 STAMFORD\n15000 2015 STAMFORD\n20000 2015 STAMFORD\n24000 2015 STAMFORD\n12000 2015 STAMFORD"
for line in sys.stdin:
  newline = newline+"\n"+line
  texto=texto+newline

reducir(procesar(texto))